//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MultiligaApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class druzyna
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public druzyna()
        {
            this.zawodnik_druzyna = new HashSet<zawodnik_druzyna>();
        }
    
        public int id_druzyna { get; set; }
        public int id_kapitan { get; set; }
        public string nazwa { get; set; }
    
        public virtual zawodnik zawodnik { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<zawodnik_druzyna> zawodnik_druzyna { get; set; }
    }
}
