//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MultiligaApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class druzyna_zawody
    {
        public int id_druzyna_zawody { get; set; }
        public int id_druzyna { get; set; }
        public int id_zawody { get; set; }
        public bool zaakceptowane { get; set; }
    
        public virtual druzyna druzyna { get; set; }
        public virtual zawody zawody { get; set; }
    }
}
