//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MultiligaApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class kapitan
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public kapitan()
        {
            this.druzyna = new HashSet<druzyna>();
            this.zawodnik1 = new HashSet<zawodnik>();
        }
    
        public int id_kapitan { get; set; }
        public int id_opiekun_zawodow { get; set; }
        public int id_zawodnik { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<druzyna> druzyna { get; set; }
        public virtual opiekun_zawodow opiekun_zawodow { get; set; }
        public virtual zawodnik zawodnik { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<zawodnik> zawodnik1 { get; set; }
    }
}
