//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MultiligaApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class pakiet_startowy
    {
        public int id_pakiet_startowy { get; set; }
        public int id_kurier { get; set; }
        public string alarm { get; set; }
        public int numer { get; set; }
        public string nadajnik { get; set; }
    
        public virtual pracownik pracownik { get; set; }
    }
}
