//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MultiligaApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class wplata
    {
        public int id_wplaty { get; set; }
        public int id_zawodnik { get; set; }
        public int id_ksiegowa { get; set; }
        public int id_opiekun_zawodow { get; set; }
        public short przelew_wykonany { get; set; }
    
        public virtual pracownik pracownik { get; set; }
        public virtual pracownik pracownik1 { get; set; }
        public virtual zawodnik zawodnik { get; set; }
    }
}
