//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MultiligaApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class wplata
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public wplata()
        {
            this.zawodnik = new HashSet<zawodnik>();
        }
    
        public int id_wplaty { get; set; }
        public int id_ksiegowa { get; set; }
        public int id_opiekun_zawodow { get; set; }
        public short przelew_wykonany { get; set; }
    
        public virtual ksiegowa ksiegowa { get; set; }
        public virtual opiekun_zawodow opiekun_zawodow { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<zawodnik> zawodnik { get; set; }
    }
}
