//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MultiligaApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class zawodnik
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public zawodnik()
        {
            this.kapitan = new HashSet<kapitan>();
            this.wplata = new HashSet<wplata>();
            this.ranking_cyklu = new HashSet<ranking_cyklu>();
            this.wynik_wyscigu = new HashSet<wynik_wyscigu>();
            this.cykl = new HashSet<cykl>();
            this.wyscig = new HashSet<wyscig>();
            this.zawody = new HashSet<zawody>();
        }
    
        public int id_zawodnik { get; set; }
        public int id_uzytkownik { get; set; }
        public Nullable<int> id_kapitan { get; set; }
        public Nullable<int> id_druzyna { get; set; }
        public Nullable<int> wiek { get; set; }
        public Nullable<int> wzrost { get; set; }
        public Nullable<int> waga { get; set; }
        public Nullable<int> osiagniecia { get; set; }
        public Nullable<short> publiczne { get; set; }
        public string imie_nazwisko { get; set; }
    
        public virtual druzyna druzyna { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<kapitan> kapitan { get; set; }
        public virtual kapitan kapitan1 { get; set; }
        public virtual ranking_globalny ranking_globalny { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<wplata> wplata { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ranking_cyklu> ranking_cyklu { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<wynik_wyscigu> wynik_wyscigu { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<cykl> cykl { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<wyscig> wyscig { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<zawody> zawody { get; set; }
    }
}
