//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MultiligaApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class zawody
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public zawody()
        {
            this.zawodnik = new HashSet<zawodnik>();
        }
    
        public int id_zawody { get; set; }
        public string dyscyplina { get; set; }
        public int id_kwalifikacje { get; set; }
        public string cykl { get; set; }
        public System.DateTime data { get; set; }
        public int id_opiekun_zawodow { get; set; }
    
        public virtual kwalifikacje kwalifikacje { get; set; }
        public virtual pracownik pracownik { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<zawodnik> zawodnik { get; set; }
    }
}
